name: lsir
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - jupyterlab
  - seaborn
  - pip
  - pip:
    - pyarrow
    - tweepy
    - matplotlib
    - plotly
    - ruptures
    - pandarallel
    - fasttext
    - nltk
    - emoji
    - spacy
