name: lsir
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - jupyterlab
  - seaborn
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio 
  - cudatoolkit=11.3
  - pip
  - pip:
    - pyarrow
    - tweepy
    - matplotlib
    - plotly
    - ruptures
    - pandarallel
    - fasttext
    - nltk
    - emoji
    - spacy
    - scikit-learn
    - transformers
